aws:
  region: ${AWS_REGION:ap-south-2}
  s3:
    bucket: leaderapp-media-india
  credentials:

    accessKey: ${AWS_ACCESS_KEY_ID:dummy}
    secretKey: ${AWS_SECRET_ACCESS_KEY:dummy}


spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB
